fix add support for intercept in SqrtLasso
scikit-learn-contrib/skglm pull request #214
Opened 2023-12-14 09:37 UTC by PascalCarrivain

## Context of the PR

This PR adds support for intercept in `SqrtLasso` estimator.
Closes #96 

### Checks before merging PR

- [ ] added documentation for any new feature
- [ ] added unittests
- [ ] edited the [what's new](../doc/changes/whats_new.rst)

2023-12-15 09:37 UTC, Badr-MOUFAD reviewed
Thanks @PascalCarrivain for the PR!
Here are some remarks

2023-12-15 09:37 UTC, Badr-MOUFAD commented on skglm/experimental/sqrt_lasso.py
> +                if self.fit_intercept:
Here we are inverting the cases, therefore it break the CI

2023-12-15 09:37 UTC, Badr-MOUFAD commented on skglm/experimental/sqrt_lasso.py
> +                    res_norm = norm(y - X @ coef)
WDYT about this implementation to make it more precise?

```suggestion
                X_coef = X @ coef if not fit_intercept else X @ coef[:-1] + coef[-1]
                res_norm = norm(y - X_coef)
```

2024-02-22 13:01 UTC, mathurinm commented on skglm/experimental/sqrt_lasso.py
> +                if self.fit_intercept:
There's duplicated here, I'd just put the definition of  Xw_init in the if else, but then coef, _, _ = ... can be factorized outside

2024-02-29 22:07 UTC, Badr-MOUFAD reviewed
Many thanks Pascal for the hard work :muscle:

Just a small bit before merging

We didn't add tests for the intercept (might be vulnerable to bugs later)

I'm not aware of any package to check against it the new feature, any suggestions @mathurinm?

With that being said, we can leverage the equivalence between the problem with intercept and without as the datafit is a norm_2 hence setting its gradient w.r.t. the intercept to zero implies setting the residual to zero

$$
\\begin{equation}
\\min_{w, w_0} \\| y - (Xw - w_0 \mathbb{1})  \\| + \\lambda \\| w \\|_1  \\Longleftrightarrow
\\begin{cases}
\\min_w & \\| \\bar{y} - \\bar{X}w \\| + \\lambda \\| w \\|_1 \\\\
\\text{where} & w_0 = \\text{mean}(y) - \\langle \\text{mean\\_col}(X), \\hat{w} \\rangle
\\end{cases}
\\end{equation}
$$

2024-02-29 22:07 UTC, Badr-MOUFAD commented on skglm/experimental/tests/test_sqrt_lasso.py
> +        np.testing.assert_equal(sqrt_lasso.coef_, 0)
WDYT about this refactoring?

```suggestion
    np.testing.assert_equal(sqrt_lasso.coef_[:n_features], 0)
```

2025-04-07 15:02 UTC, mathurinm commented
@PascalCarrivain thanks for bringing this up again ; there's a conflict that needs to be solved

Also @Badr-MOUFAD how could we test against a Lasso solver ? Do you remember some formula linking the regularization strentgth of the Lasso to that of the sqrt Lasso ? 
Should we, one some particular data, find by dichotomy two values of lambda that give the same solution for Lasso and SqrtLasso, and then hardcode them in a test ? It sounds good enough for me, there hasn't been a crushing pressure for this feature...

2025-04-16 09:34 UTC, mathurinm commented
Using this works: 
$$\lambda_{sqrt} = \frac{n \lambda_{lasso} }{\Vert y - X\hat \beta_{lasso} \Vert}$$
```
import numpy as np
from numpy.linalg import norm
from skglm import Lasso
from skglm.experimental import SqrtLasso

np.random.seed(0)
X = np.random.randn(10, 20)
y = np.random.randn(10)

n = len(y)

alpha_max = norm(X.T @ y, ord=np.inf) / n

alpha = alpha_max / 10

lass = Lasso(alpha=alpha, fit_intercept=False, tol=1e-8).fit(X, y)
w_lass = lass.coef_
assert norm(w_lass) > 0

scal = n / norm(y - X @ w_lass)

sqrt = SqrtLasso(alpha=alpha * scal, tol=1e-8).fit(X, y)

print(norm(w_lass - sqrt.coef_))  # this is 1e-8
```


this is not the usual equivalence (one would expect a sqrt(n) not a n, so that $\lambda_{sqrt} = \lambda_{lasso} / \hat{sigma}$), but this is because our SqrtLasso objective does not have the 1/sqrt(n) normalization in front of the datafit


@floriankozikowski when an intercept is fitted the scaling factor should just be `scal = n / norm(y - sqrt.predict(X))`

2025-04-16 09:38 UTC, mathurinm commented
Ok this works on the PR:
```
import numpy as np
from numpy.linalg import norm
from skglm import Lasso
from skglm.experimental import SqrtLasso

np.random.seed(0)
X = np.random.randn(10, 20)
y = np.random.randn(10)
y += 1

n = len(y)

alpha_max = norm(X.T @ y, ord=np.inf) / n

alpha = alpha_max / 10

lass = Lasso(alpha=alpha, fit_intercept=True, tol=1e-8).fit(X, y)
w_lass = lass.coef_
assert norm(w_lass) > 0

scal = n / norm(y - lass.predict(X))

sqrt = SqrtLasso(alpha=alpha * scal, fit_intercept=True, tol=1e-8).fit(X, y)
```

but we have a problem, sqrt.coef_ is 1 coefficient too long, because we still store the intercept as last value. This is easy to fix @PascalCarrivain

2025-04-22 14:09 UTC, mathurinm requested changes

2025-04-22 14:09 UTC, mathurinm commented on skglm/experimental/sqrt_lasso.py
> +            self.intercept_ = self.coef_[-1]
@PascalCarrivain you also need to make self.coef_ shorter by one element in that case, otherwise it still contains the itnercept as last value

2025-04-23 09:32 UTC, mathurinm commented on .DS_Store
@floriankozikowski remove these 3 files

2025-04-23 10:13 UTC, mathurinm commented
This has become hard to read due to git errors, closing in favor of the restart #298

2025-04-23 10:13 UTC, closed without merging