[WIP] MAINT - use AA class in ``cd_solver``
scikit-learn-contrib/skglm pull request #33
Opened 2022-06-21 09:03 UTC by Badr-MOUFAD

This aims to refactor ``cd_solver``.

It will proceed as follows:

- [ ] use AA class instead
- [ ] hide ``use_acc`` from the API
- [ ] perform benchmark against main

2022-06-23 16:45 UTC, Badr-MOUFAD commented on skglm/solvers/multitask_bcd_solver.py
> +                                           XW_acc.reshape(-1, n_tasks))
@mathurinm, I m not sure whether I pass in a view or a copy.

Link to [reshape Numpy doc ](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#:~:text=Returns,the%20returned%20array.)

2022-06-24 13:26 UTC, Badr-MOUFAD commented
Here are [the results of the benchmark](https://badr-moufad.github.io/share-benchmarks/) to ensure that switching to AA class won't deteriorate the performance of the solver.

I'm satisfied with the results for the ``cd_solver``, yet not that convinced with those of the multitask solver. I suspect that this https://github.com/scikit-learn-contrib/skglm/pull/33#discussion_r905250846 is the reason behind but still quite unsure.

2022-06-24 13:33 UTC, PABannier commented
i think there's an issue with the curves @Badr-MOUFAD . All the suboptimality gaps are going up (Lasso and MTL).

2022-06-24 15:11 UTC, Badr-MOUFAD commented
@PABannier, that was a nice catch indeed! I was blinded by the shape of the figures.
There was a bug in the computation of the objective. In fact, I use solver path in the benchmarks, which outputs an array of the coefs along the path and not a single coef.

I fixed that and here are [the new figures](https://badr-moufad.github.io/share-benchmarks/).

2022-06-24 16:52 UTC, PABannier commented
LGTM! For the performance on the MTL, remember that Numba is not as performing as in the single task case. MTL is not very fast actually.

2022-07-13 09:59 UTC, mathurinm requested changes

2022-07-13 09:59 UTC, mathurinm commented on skglm/solvers/cd_solver.py
> +            w_acc, Xw_acc = accelerator.extrapolate(w, Xw)
This design is not optimal: K - 1 times out of K, we just return w and Xw, so there is no need to compute p_obj_acc. A third variable, boolean, should be returned, and checking of Xw_acc done only if acceleration is performed

2022-07-14 22:00 UTC, QB3 commented
Just to let you know, in my experience computing the quantity `Xwacc`  using the `K` last `Xw` (as it is done here  https://github.com/scikit-learn-contrib/skglm/blob/9b7f3ef89c5261002ace2d804245a6d934023cb5/skglm/utils.py#L300) often yielded numerical errors (as you noticed) but also slower convergence. I usually had to recompute `Xwacc` using `X @ wacc`

2022-07-18 12:43 UTC, Badr-MOUFAD commented
I pulled main to integrate changes that address https://github.com/scikit-learn-contrib/skglm/pull/33#discussion_r919887164
Here are the results of the [benchmark](https://badr-moufad.github.io/share-benchmarks/multitask_solver/benchmark_aa_multi_benchopt_run_2022-07-18_14h09m20.html) on datasets with sizes (100, 1000) and (100, 3000)

> ... often yielded numerical errors (as you noticed) ...

@QB3 can you pls hint me at those numerical errors?


With that being said, I see two areas for improving MTL

- [ ] Extend AA class to handle the case of ``W`` matrix.
  so far, we get around that by flattening ``W`` which results in extra-memory copies of ``W``
  (c.f. [L248-249](https://github.com/Badr-MOUFAD/skglm/blob/9b27d8ab60b950ab70f06d445a79a3fd7e08ec28/skglm/solvers/multitask_bcd_solver.py#L248-L249)  and [L253-253](https://github.com/Badr-MOUFAD/skglm/blob/9b27d8ab60b950ab70f06d445a79a3fd7e08ec28/skglm/solvers/multitask_bcd_solver.py#L252-L253))

- [ ] Atler AA to accelerate only the features in ``ws``.
This is relevant in the case of a solution with small support  

--------------

If these seem right, I shall tackle them in a separate PR

2022-07-25 07:37 UTC, mathurinm commented on skglm/solvers/cd_solver.py
>                  # TODO : manage penalty.value(w, ws) for weighted Lasso
can you move the todo to keep it next to the line of code it applies to (the p_obj computation)

2022-07-25 07:37 UTC, mathurinm commented on skglm/solvers/multitask_bcd_solver.py
> +        p_obj = datafit.value(Y, W[ws, :], XW) + penalty.value(W)
here W is restricted to ws, above it's not. Is one better than the other ?

2022-07-25 09:16 UTC, Badr-MOUFAD commented
For conciseness, this PR will focus on ``_cd_solver`` only.
MLT deserves its own PR.

2022-07-25 09:58 UTC, Badr-MOUFAD commented on skglm/solvers/cd_solver.py
> -            last_K_w = np.zeros([K + 1, ws_size])
solved by passing w[ws] to AA instead of the entire vector

2022-07-25 11:26 UTC, Badr-MOUFAD commented
Here are the [result of the benchmark](https://badr-moufad.github.io/share-benchmarks/cd_solver/benchmark_aa_single_benchopt_run_2022-07-25_13h19m55.html) for the cd_solver.
@mathurinm, I will perform a benchmark on the finance dataset to answer https://github.com/scikit-learn-contrib/skglm/pull/33#discussion_r928651847

2022-07-25 11:51 UTC, Badr-MOUFAD commented on skglm/solvers/cd_solver.py
> -            last_K_w = np.zeros([K + 1, ws_size])
@mathurinm,
link to [benchmark on finance dataset](https://badr-moufad.github.io/share-benchmarks/cd_solver_finance/benchmark_aa_single_benchopt_run_2022-07-25_13h43m34.html)

2022-07-25 14:10 UTC, PABannier commented
LGTM @Badr-MOUFAD !

2022-07-25 14:18 UTC, QB3 commented
Thanks a lot for the PR @Badr-MOUFAD !

Implementation with the class seems to yield faster results, do you think it is because `X_w_acc` is not recomputed anymore when extrapolating?

![Screenshot from 2022-07-25 10-16-41](https://user-images.githubusercontent.com/20907043/180798832-60e0c8b7-e876-4fe2-9c10-9c94eedec05c.png)

2022-07-25 14:24 UTC, QB3 commented
> Here are the [result of the benchmark](https://badr-moufad.github.io/share-benchmarks/cd_solver_simulated/benchmark_aa_single_benchopt_run_2022-07-25_13h19m55.html) for the cd_solver.

just to be 100% sure that there is no regression with respect to main, can you make the same benchmark on rcv1, new20, finance, with lambda_max / 10, lambda_max / 100, lambda_max / 1000

2022-07-25 22:04 UTC, Badr-MOUFAD commented
@QB3, as requested, here is the [full benchmark](https://badr-moufad.github.io/share-benchmarks/cd_solver/benchmark_aa_single_benchopt_run_2022-07-25_23h48m09.html) on finance, rvc1, news20, and simulated data.

> Implementation with the class seems to yield faster results, do you think it is because X_w_acc is not recomputed anymore when extrapolating?

Frankly, I haven't profiled the AA code. But recomputing ``Xw_acc`` is certainly a reason among (potentially) others.

2022-07-26 20:06 UTC, QB3 commented
Thanks you so much for the hard work and the benchmark @Badr-MOUFAD .

One last (collective) question: do we want to remove the parameters for the activation / deactivation of Anderson acceleration? as well as the number of iterations? (I have no strong takes, I just want to be sure everyone is OK with it).
Apart from this LGTM!

2022-07-27 08:34 UTC, Badr-MOUFAD commented
> One last (collective) question: do we want to remove the parameters for the activation / deactivation of Anderson acceleration? as well as the number of iterations? (I have no strong takes, I just want to be sure everyone is OK with it).

actually, AA is used either way as it's one of the features of ``skglm`` solvers. We've previously had a [small discussion](https://github.com/scikit-learn-contrib/skglm/pull/29#discussion_r901695736) about that.

One relevant use case of exposing these parameters is when debugging/comparing solvers. Yet, we can still manage that in a separate branch and keep the API simple. we had also [a discussion](https://github.com/mathurinm/celer/pull/267) on that with @mathurinm.

2022-07-27 08:39 UTC, PABannier commented
I think the API should be kept as minimal as possible.

2022-08-26 19:05 UTC, QB3 commented
Should we merge?

2022-08-29 07:23 UTC, mathurinm commented
The benchmark results look good, conflict need to be fixed and then we can do a final round of reviews

2022-08-29 10:37 UTC, mathurinm approved these changes

2022-08-29 12:58 UTC, merged