DOC add `Whatsnew` section
scikit-learn-contrib/skglm pull request #75
Opened 2022-09-19 19:49 UTC by PABannier

Since `skglm` is growing bigger, we need to keep track of contributions and API changes in the library. 
This PR introduces a `Whatsnew` section with a `changes` folder in the `doc`.
I got inspired by [MNE-Python](https://github.com/mne-tools/mne-python) template. WDYT?

Closes #71

2022-09-29 11:41 UTC, Badr-MOUFAD reviewed
Thanks @PABannier for this PR.
I have one concern. These changes were (presumably) written manually. I wonder how to keep the whats_new synchronized with the current changes in the package. For instance here, I see two missing major changes:
- Group solver
- API changes in solvers (function --> class)

2022-09-29 11:47 UTC, mathurinm commented
Good point. In sklearn and benchopt, we do it manually which makes me think they're no easy solution

Here it was costly to do because we had to track back all changes. Now we only need to require it for every merged PR, it'll be easier.

2022-09-29 13:22 UTC, PABannier commented
Yup agreed. I was off for a month, so I probably forgot a few additions.
In the future, for every major PR, we should require to document changes in the changelog file. That's how it's done in MNE-Python.

2022-09-29 19:06 UTC, Badr-MOUFAD reviewed
Just a small point to discuss before merging

2022-09-29 19:06 UTC, Badr-MOUFAD commented on doc/sphinxext/gh_substitutions.py
> +"""Provide a convenient way to link to GitHub issues and pull requests.
Nice reflex @mathurinm to group the sphinx py modules in a separate folder.
We should consider doing the same for ``github_link.py`` (in another PR)

2022-09-29 19:22 UTC, PABannier commented on doc/changes/0.1.rst
> +- Accelerated coordinate descent solver with a working set strategy
Agreed

2022-09-30 07:04 UTC, mathurinm commented on doc/changes/0.1.rst
> +- Accelerated coordinate descent solver with a working set strategy
agreed too !

2022-09-30 15:47 UTC, Badr-MOUFAD approved these changes
LGTM!

2022-09-30 15:49 UTC, mathurinm requested changes

2022-09-30 15:49 UTC, mathurinm commented on doc/changes/0.2.rst
> +- Proximal Newton solver with working sets for problems with non-quadratic datafits (:gh:`51`)
can you put the name of the class here (as for datafits?). It guides the user to the correct class

2022-09-30 15:49 UTC, mathurinm commented on doc/changes/0.2.rst
> +- SCAD and Block SCAD penalties supported (:gh:`12`)
class names here too

2022-09-30 15:49 UTC, mathurinm commented on doc/changes/0.2.rst
> +- Gram coordinate descent solver (:gh:`59`)
class name here too

2022-09-30 15:49 UTC, mathurinm commented on doc/changes/0.2.rst
> +- Proximal Newton solver with working sets for problems with non-quadratic datafits (:gh:`51`)
even better if you manage to link to the doc of the corresponding class...

2022-09-30 19:16 UTC, mathurinm commented on doc/changes/0.2.rst
> +- Proximal Newton solver with working sets for problems with non-quadratic datafits (:gh:`51`)
we should :)

2022-10-03 06:34 UTC, mathurinm commented
I changed the way links are formatted; Scad, BlockSCAD and GramCD don't appear because they are missing from the doc.

@Badr-MOUFAD could you add them to `api.rst`, with all the other solvers?

2022-10-05 08:33 UTC, mathurinm commented
Links for scad and blockscad are not working (+ I get warnings when running `make html-noplot`)

When this is fixed, go for merge!

2022-10-05 09:36 UTC, Badr-MOUFAD commented
They don't appear as they are not included in the API ...

2022-10-05 10:08 UTC, mathurinm commented
so, they should be included in the API. it can be done in this PR

2022-10-05 15:53 UTC, merged

2022-10-05 15:53 UTC, mathurinm commented
thank you all